## EAS 503 Homework 4 Submission
Name - _Enter your name here_

**Make sure that you rename the notebook file to *replacewithubitname*_eas503_hw3.ipynb**


### Submission Details 
* **Due Date** - November 28, 2017 by 11.59 PM PST. All assignments have to be submitted using UBLearns.
* **Number of Problems** - 1 
* **Maximum points** - 50
* **Collaboration policy**
 - Every student has to submit individual homeworks
 - Any collaboration, in the form of discussion, with other members of the class is permitted, as long as the names of the collaborating members are explicitly stated on top of the submitted homework.
 - Any overlap with another submission or material from Internet will be awarded an F.
* **Late submission policy** - _No late submissions allowed_
* **Submission Format** - Enter code for each problem in the appropriate cell below. You may use multiple cells for a single problem to improve readability.

### Problem 1 - Chicago Crime Dataset (50 points)

Recall the Chicago Crime Data that was used in HW3. In this HW you are provided with 3 data files namely `chicago_crime_data_1.csv`, `chicago_crime_data_2.csv` and `primary_type_id.csv`.  The `chicago_crime_data_1.csv` contains data pertaing to the details of the crime and the `chicago_crime_data_2.csv` has information about the location and type. Both the datasets have the Crime ID as the primary indicator. 

The `primary_type_id.csv` contains the mapping between the primary crime type to their corresponding ID.

Using pymysql import the chicago crime data. Check if the data format are correct. In this problem, you will be asked to create a single sql query that will result in the desired output. Wherever required, provide the algebraic expressions and expression trees.

1. What is the average crime rate in each year? (Query)

2. Subset the list of crimes that occured at SIDEWALK and an arrest has been made. (Query, algebraic expression and expression tree)

3. In the resulting dataset, identify the crime type that resulted in most crimes per each district. (Query)

4. List the crimes with FBI code = 26 and domestic? (Query, algebraic expression and expression tree) 

5. What is the increase in the number of crimes involving thefts (primary crime type) from 2016 to 2017? (Query)

6. What are the 3 most common types of crimes in `001XX N PARKSIDE AVE`? Provide the corresponding crime counts for these crime types. (Query)

7. Average days between the crime indcident date and last updated date. (Query)

8. List the crimes that were committed on `4/30/2016` and updated on the same day. (Query, algebraic expression, expression tree)

9. Subset the list of crimes in 2016 that were domestic and occured on a `STREET` and an arrest was made. (Query, algebraic expression, expression tree)

10. Are there any crimes that involved `Telephone threats` that occured in Disctric `10` and FBI code `30`? (Query, algebraic expression, expression tree)


Submit the SQL query as a .txt file. The algebraic expressions and expression tree can hand written and submitted through UBLearns as a single PDF file.

In [2]:
#Enter your solution here
import pandas as pd
df=pd.read_csv("chicago_crime_data_1.csv")

In [ ]:
import pymysql
conn = pymysql.connect(user='root',passwd='brainchamp',db='test',charset='utf8')
print(conn)
cur = conn.cursor()
print(cur)

In [3]:
df

,Crime_ID,Case Number,Date,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code
0,10496347,HZ237390,4/23/2016 16:55,False,False,1512,15,29.0,25,14
1,10496348,HZ237355,4/23/2016 14:00,False,False,111,1,42.0,32,6
2,10496349,HZ237341,4/23/2016 16:10,True,False,915,9,11.0,34,04B
3,10496350,HZ237330,4/23/2016 13:30,False,False,1624,16,38.0,15,3
4,10496351,HZ237402,4/23/2016 16:45,False,True,632,6,8.0,44,26
5,10496352,HZ237376,4/23/2016 16:39,False,True,1021,10,24.0,29,6
6,10496353,HZ237358,4/23/2016 7:00,False,False,1834,18,42.0,8,6
7,10496354,HZ237396,4/23/2016 12:00,False,True,1024,10,22.0,30,26
8,10496355,HZ237254,4/23/2016 1:00,False,True,331,3,5.0,43,26
9,10496356,HZ237248,4/23/2016 15:10,False,False,431,4,10.0,51,14
10,10496360,HZ237394,4/23/2016 16:58,False,False,2211,22,19.0,74,14
11,10496361,HZ237371,4/23/2016 9:00,False,False,422,4,7.0,46,5
12,10496362,HZ237399,4/23/2016 17:00,False,True,431,4,10.0,51,08A
13,10496365,HZ237135,4/23/2016 13:15,False,False,411,4,5.0,43,6
14,10496368,HZ237362,4/23/2016 13:30,False,False,1814,18,43.0,7,6
15,10496369,HZ237241,4/23/2016 14:50,False,True,932,9,16.0,61,14
16,10496370,HZ237354,4/23/2016 16:30,True,False,2422,24,49.0,1,6
17,10496372,HZ237331,4/23/2016 15:59,False,True,1421,14,26.0,23,04A
18,10496378,HZ237366,4/23/2016 16:30,False,False,431,4,10.0,51,14
19,10496379,HZ237455,4/23/2016 18:03,False,False,924,9,12.0,61,6
20,10496380,HZ237448,4/23/2016 17:30,False,False,2213,22,19.0,72,6
21,10496382,HZ237374,4/23/2016 12:37,False,False,2431,24,49.0,1,6
22,10496387,HZ237352,4/23/2016 1:00,False,False,1711,17,50.0,13,3
23,10496388,HZ237474,4/23/2016 9:20,False,False,934,9,16.0,61,6
24,10496390,HZ237477,4/23/2016 15:00,False,False,414,4,7.0,43,14
25,10496391,HZ237391,4/23/2016 16:52,False,True,423,4,7.0,46,08B
26,10496392,HZ237345,4/23/2016 6:00,False,False,634,6,21.0,49,7
27,10496393,HZ237485,4/23/2016 18:15,False,False,414,4,7.0,43,14
28,10496394,HZ237299,4/23/2016 7:45,False,True,2532,25,37.0,25,26
29,10496396,HZ237332,4/23/2016 14:15,False,False,312,3,20.0,42,08B
...,...,...,...,...,...,...,...,...,...,...
436234,10496273,HZ237193,4/23/2016 13:00,False,False,921,9,12.0,58,08B
436235,10496276,HZ237170,4/23/2016 2:00,False,False,1832,18,42.0,8,11
436236,10496277,HZ237253,4/23/2016 12:00,False,False,1511,15,29.0,25,11
436237,10496278,HZ237301,4/23/2016 6:00,False,False,1422,14,26.0,23,14
436238,10496281,HZ237220,4/23/2016 13:55,True,False,2233,22,34.0,73,18
436239,10496283,HZ237168,4/23/2016 13:10,False,False,823,8,15.0,66,26
436240,10496287,HZ237282,4/23/2016 15:20,False,False,1614,16,41.0,10,6
436241,10496289,HZ237223,4/23/2016 14:30,False,True,1033,10,12.0,30,08B
436242,10496293,HZ237130,4/23/2016 10:00,False,False,913,9,11.0,60,6
436243,10496299,HZ237194,4/23/2016 12:05,False,False,1824,18,42.0,8,6
436244,10496300,HZ237289,4/23/2016 1:30,False,False,1823,18,27.0,8,11
436245,10496304,HZ237214,4/23/2016 14:10,True,False,1522,15,28.0,25,6
436246,10496306,HZ237309,4/23/2016 15:30,False,True,1933,19,44.0,6,08B
436247,10496308,HZ237238,4/23/2016 15:00,False,False,1223,12,2.0,28,14
436248,10496309,HZ237279,4/23/2016 14:45,False,False,2024,20,48.0,3,08A
436249,10496310,HZ237259,4/23/2016 15:10,False,False,1533,15,28.0,25,08B
436250,10496313,HZ237260,4/23/2016 15:08,False,False,224,2,3.0,38,10
436251,10496315,HZ237150,4/23/2016 8:00,False,False,923,9,14.0,63,08A
436252,10496317,HZ237154,4/23/2016 12:30,False,False,912,9,11.0,59,26
436253,10496318,HZ237137,4/23/2016 13:17,True,False,833,8,13.0,65,6
436254,10496319,HZ237265,4/23/2016 14:10,True,False,623,6,17.0,69,6
436255,10496321,HZ237292,4/23/2016 14:20,False,False,322,3,6.0,69,10
436256,10496322,HZ237302,4/23/2016 14:38,False,False,1011,10,24.0,29,04B
436257,10496325,HZ237337,4/23/2016 15:45,True,False,424,4,10.0,46,18
436258,10496332,HZ237318,4/23/2016 15:40,True,False,112,1,42.0,32,6
436259,10496334,HZ237389,4/23/2016 2:00,False,False,2511,25,29.0,19,14
436260,10496337,HZ237380,4/23/2016 9:00,False,False,1632,16,36.0,17,6
436261,10496339,HZ237230,4/23/2016 12:00,False,False,1511,15,29.0,25,6
436262,10496341,HZ237435,4/23/2016 15:00,False,False,122,1,2.0,32,6
436263,10496344,HZ237360,4/23/2016 16:22,True,False,1024,10,22.0,30,26